export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
 
export default function PlansAndPricingLayout({ children }) {
 return (
    <div>
      <p>Plans And Pricing</p>
      <div>{children}</div>
    </div>
  )
}

